/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.pmw.tinylog.Logger;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Logger.info("My first log entry");
        Logger.debug("Debug");
        Logger.warn("Warning");
        Logger.error("Error");
    }
}
